import { loadGameContext } from './helpers.mjs';
const ctx = loadGameContext();
ctx.setState(ctx.deep(ctx.baseState));
const state = ctx.getState();
state.hero = { name: 'Smoke', classId: 'bard', origin: 'ambitious', attrs: { ...ctx.classes.bard.attrs } };
state.seed = 'SMOKE'; state.rngState = ctx.hashSeed(state.seed);
ctx.initQuests(); ctx.initVoters(); ctx.initSurprises(); ctx.initLivingWorld(); ctx.normalizeState();
ctx.completeQuest('register');
const mapActivities = ctx.getActivities('pub');
if (!mapActivities.length) throw new Error('Map has no pub activities');
const quest = ctx.questDefs.register;
if (!quest || ctx.getState().quests.register?.status !== 'done') throw new Error('Quest flow failed');
ctx.getState().quests.debate = { status: 'active', started: 1 };
const debateGrade = ctx.simulateDebate('mixed');
if (!debateGrade || ctx.getState().debate.active) throw new Error('Debate simulation did not complete');
ctx.finalizeElection();
if (typeof ctx.getState().flags.vote !== 'number' || typeof ctx.getState().flags.seats !== 'number') throw new Error('Election did not calculate');
if (ctx.getState().flags.seats < ctx.getState().flags.majority && !ctx.getState().coalition.active && !ctx.getState().ended) throw new Error('Coalition did not initialize when needed');
console.log('smoke ok');
