import assert from 'node:assert/strict';
import { loadGameContext } from './helpers.mjs';

const ctx = loadGameContext();
ctx.startCampaignForTest();
assert.equal(ctx.getStateForTest().phase, 'event');
ctx.showMap();
assert.equal(ctx.getStateForTest().phase, 'map');
assert.ok(Object.keys(ctx.locations).length >= 1, 'map locations available');
const questId = Object.keys(ctx.questDefs)[0];
ctx.startQuestForTest(questId);
assert.equal(ctx.getStateForTest().currentEvent, questId);
ctx.getStateForTest().quests.debate = { status: 'active' };
ctx.startDebate();
assert.ok(ctx.getStateForTest().debate.active, 'debate initialized');
const result = ctx.calculateElectionForTest();
assert.ok(result && Number.isFinite(result.playerSeats), 'election calculation returns seats');
ctx.startCoalitionForTest(result);
assert.ok(ctx.getStateForTest().coalition.active, 'coalition initialized');
console.log('smoke ok');
