import assert from 'node:assert/strict';
import vm from 'node:vm';
import { loadGameContext, readText } from './helpers.mjs';

const context=loadGameContext();
for(const file of ['src/v0142.js','src/v0142c.js','src/v0142d.js','src/v0142-stability.js','src/v0142-countercampaign.js','src/v0142-ui-balance.js','src/v0142-clarity.js','src/state.js','src/save-system.js','src/v0143.js']) vm.runInContext(readText(file),context,{filename:file});
context.clearStoredSavesForTest();
context.setStoredSaveForTest('koryto_v013',{version:'0.13',day:3,actions:2,phase:'map',hero:{name:'Legacy Kandidát',classId:'bard',attrs:{charisma:9}},stats:{influence:12,trust:67},flags:{legacyMarker:true}});
const loaded=context.KorytoSaveSystem.loadGame();
assert.equal(loaded.hero.name,'Legacy Kandidát');
assert.equal(loaded.hero.attrs.charisma,9);
assert.equal(loaded.stats.influence,12);
assert.equal(loaded.flags.legacyMarker,true);
assert.equal(loaded.version,'0.14.3-test.2');
assert.equal(loaded.phase,'map');
assert.equal(context.KorytoState.validate(loaded).length,0);
assert.equal(context.KorytoSaveSystem.roundTrip(loaded).ok,true);
const simulations=context.runSimulationForTest(20,15000);
assert.equal(simulations.every(result=>result.ended),true);
const index=readText('index.html');
assert.match(index,/0\.15\.2 TEST\.1/);
assert.match(index,/src\/v0146-playtest\.js/);
assert.match(index,/src\/v0148-visual-system\.js/);
assert.match(index,/src\/v0149-pixel-assets\.js/);
assert.match(index,/src\/v0152-reference-match\.js/);
assert.doesNotMatch(index,/src\/v0142-rc3\.js/);
assert.equal(readText('VERSION').trim(),'0.15.2-test.1');
console.log('legacy RC3 regressions remain covered in layered v0.15.2 TEST.1');
