"use strict";
(() => {
  const VERSION = "0.14.4 TEST.6";
  const clampLocal=(n,a,b)=>Math.max(a,Math.min(b,n));
  function councilResult(vote){const totalSeats=15,majority=8,seats=Math.max(1,Math.min(14,Math.round(vote/100*totalSeats)));return {totalSeats,majority,seats,needs:Math.max(0,majority-seats)};}
  function coalitionCapacity(target){return target.stats.influence*.28+target.stats.leverage*.75+Math.max(0,target.factions.citizens)*.08+Math.max(0,target.factions.jzd)*.07+Math.max(0,target.factions.business)*.07+Math.max(0,target.factions.officials)*.08-(target.promiseSummary?.broken||0)*4-target.stats.heat*.04-(target.debt||0)*.2;}
  function projection(target,voters){let ballots=0,votes=0;for(const [id,d] of Object.entries(voters)){const v=target.voters[id]||{support:d.base,turnout:d.turnout};const b=d.population*v.turnout;ballots+=b;votes+=b*v.support/100;}let center=Math.round(votes/Math.max(1,ballots)*.72+target.stats.support*.18+target.stats.trust*.06-target.stats.heat*.025-(target.debt||0)*.08);if(target.conspiracy?.exposed)center+=3;if(target.conspiracy?.joined&&target.conspiracy?.resolved)center+=4;center=clampLocal(center,5,70);const uncertainty=Math.max(3,8-Math.floor(target.day/3)),low=clampLocal(center-uncertainty,3,70),high=clampLocal(center+uncertainty,3,72),lc=councilResult(low),hc=councilResult(high),mid=councilResult(center);return {center,low,high,seats:mid.seats,seatLow:lc.seats,seatHigh:hc.seats,majority:mid.majority};}
  function calculate(target,voters,roll){const breakdown=[];let forVotes=0,totalVotes=0;for(const [id,v] of Object.entries(voters)){const sv=target.voters[id]||{support:v.base,turnout:v.turnout};const global=(target.stats.support-50)*.11+(target.stats.trust-50)*.055-(target.stats.heat-35)*.05-(target.opponent.momentum-30)*.08+(roll-10)*.1;let machine=0;if(target.conspiracy.joined&&target.conspiracy.resolved){if(id==="entrepreneurs")machine+=28;if(id==="jzdWorkers")machine+=22;if(id==="officials")machine+=16;if(id==="club")machine+=10;if(id==="seniors")machine+=4;}if(target.conspiracy.exposed){if(id==="parents"||id==="undecided")machine+=8;if(id==="officials")machine+=5;}if(target.factionPlans.oldguard?.progress>=75&&(id==="seniors"||id==="officials"))machine-=8;const share=clampLocal(sv.support+global+machine,5,88),turnout=Math.max(.18,Math.min(.95,sv.turnout+(target.stats.support-45)*.0015)),ballots=Math.round(v.population*turnout),ours=Math.round(ballots*share/100);forVotes+=ours;totalVotes+=ballots;breakdown.push({id,name:v.name,icon:v.icon,share:Math.round(ours/Math.max(1,ballots)*100),votes:ours,ballots});}let rawVote=Math.round(forVotes/Math.max(1,totalVotes)*100);if(target.conspiracy.exposed)rawVote+=4;if(target.conspiracy.joined&&target.conspiracy.resolved)rawVote+=7;if(target.factionPlans.oldguard?.progress>=85)rawVote-=4;if(target.factionPlans.press?.progress>=90&&!target.flags.pressSpecial)rawVote-=3;const vote=clampLocal(rawVote,4,72),council=councilResult(vote);return {roll,breakdown,vote,council,capacity:coalitionCapacity(target),coalitionFormed:council.seats>=council.majority};}
  function validate(){const issues=[];for(let vote=0;vote<=100;vote+=5){const r=councilResult(vote);if(r.seats<1||r.seats>14||r.majority!==8)issues.push(`mandáty mimo rozsah pro ${vote}`);}return issues;}
  globalThis.KorytoElectionSystem={VERSION,councilResult,coalitionCapacity,projection,calculate,validate};
})();
