"use strict";
(() => {
  const VERSION = "0.14.4 TEST.3";
  const definitions=()=>globalThis.KorytoApp?.events||{};
  const resolve=id=>globalThis.KorytoApp?.eventById?.(id)||definitions()[id]||null;
  function validate(locations=globalThis.KorytoCoreData?.locations||{},quests=globalThis.KorytoQuestData?.definitions||{}){const issues=[];for(const [id,event] of Object.entries(definitions())){if(!event||typeof event!=="object"){issues.push(`${id}: událost není objekt`);continue;}if(!String(event.title||"").trim())issues.push(`${id}: chybí název`);if(!String(event.location||"").trim())issues.push(`${id}: chybí lokace`);else if(!locations[event.location])issues.push(`${id}: neznámá lokace ${event.location}`);const questId=event.questId||(quests[id]?id:null);if(questId&&!quests[questId])issues.push(`${id}: neznámý quest ${questId}`);if(event.choices!==undefined&&!Array.isArray(event.choices))issues.push(`${id}: volby nejsou pole`);for(const [index,choice] of (event.choices||[]).entries()){if(!choice||typeof choice!=="object")issues.push(`${id}[${index}]: volba není objekt`);else{if(!String(choice.label||"").trim())issues.push(`${id}[${index}]: chybí text volby`);if(!choice.check||!Number.isFinite(Number(choice.check.dc)))issues.push(`${id}[${index}]: chybí hod`);}}}return [...new Set(issues)];}
  function catalog(){const quests=globalThis.KorytoQuestData?.definitions||{};return Object.entries(definitions()).map(([id,event])=>({id,title:event.title||id,location:event.location||null,questId:event.questId||(quests[id]?id:null),queued:Boolean(event.queued),repeatable:Boolean(event.repeatable),hasAvailability:typeof event.available==="function",choices:Array.isArray(event.choices)?event.choices.length:0}));}
  function available(location,target){const app=globalThis.KorytoApp,previous=app?.getState?.();if(target&&app?.setState&&previous!==target)app.setState(target);try{return catalog().filter(item=>{if(location&&item.location!==location)return false;const event=resolve(item.id);return event&&(!(typeof event.available==="function")||event.available());});}finally{if(previous&&app?.setState&&previous!==target)app.setState(previous);}}
  function summary(){const items=catalog();return {total:items.length,repeatable:items.filter(x=>x.repeatable).length,questLinked:items.filter(x=>x.questId).length,conditional:items.filter(x=>x.hasAvailability).length,choices:items.reduce((s,x)=>s+x.choices,0),byLocation:Object.fromEntries(Object.keys(globalThis.KorytoCoreData?.locations||{}).map(id=>[id,items.filter(x=>x.location===id).length]))};}
  globalThis.KorytoEventSystem={VERSION,definitions,resolve,validate,catalog,available,summary};
})();
